### ISSUE TITLE
$pfosten crasht den Bot immer noch

### ISSUE THREAD

**Issue by Jerrynicki** [TheLastZombie/ich_iel#14]
Siehe #1

**Comment by TheLastZombie** [comment]
dann muss ich wohl das ratelimit erhöhen

**Comment by Jerrynicki** [comment]
bei einem ungültigen subreddit

**Comment by TheLastZombie** [comment]
gehts denn bei nem gülitgen oder was

**Comment by Jerrynicki** [comment]
aus #1: Wenn $pfosten zu einem ungültigen ~~(gültigen?)~~ Subreddit gespamt wird, crasht das den Bot.

**Comment by Jerrynicki** [comment]
und offensichtlich muss man nicht einmal spammen

**Comment by TheLastZombie** [comment]
war das jetzt die antwort auf meine frage

**Comment by Jerrynicki** [comment]
![image](https://user-images.githubusercontent.com/38357030/43643051-3b33c3cc-972a-11e8-8ca2-d5c2602fc752.png)

**Comment by Jerrynicki** [comment]
das ist eigentlich alles

**Comment by Jerrynicki** [comment]
welche frage

**Comment by KMikeeU** [comment]
Haha ja

**Comment by nichtdasleo** [comment]
Wa

**Comment by nichtdasleo** [comment]
roesch_iel: anstatt ein Problem zu fixen mache ich es den Usern einfach schwerer den Bot zu benutzen

**Comment by Jerrynicki** [comment]
großen danks roesch
