### ISSUE TITLE
Automatische Antworten mit Subreddit Links

### ISSUE THREAD

**Issue by nichtdasleo** [TheLastZombie/ich_iel#17]
Wie wäre es wenn der Bot auf alle Nachrichten die "/r/[subreddit]" oder "r/[subreddit]" beinhalten mit einem Link zu dem genannten Subreddit antwortet?

**Comment by Jerrynicki** [comment]
reddit aber discord

**Comment by nichtdasleo** [comment]
was

**Comment by Lexsanderiel** [comment]
wa

**Comment by Jerrynicki** [comment]
oida roesch wann implementierst du dies endlich

**Comment by TheLastZombie** [comment]
wahrscheinlich nie

hast du je nen discord bot gesehen der auf was anderes als commands reagiert

(das "hi" mit sushii zählt nicht)

wenn dann müsste das schon ein command sein, z. b. $link

**Comment by nichtdasleo** [comment]
Der Bot auf dem r/austria Subreddit macht genau das

**Comment by TheLastZombie** [comment]
ihr spammt das doch dann nur wieder

woher kennst du bitte einen bot der "vore-mention-bot" heißt

ich mache mir sorgen

**Comment by nichtdasleo** [comment]
Willst du das nur nicht machen weil du nicht weißt wie es geht?

**Comment by TheLastZombie** [comment]
ich kann das schon magen, aber dann wie gesagt in einem command, sonst nervt das ja

**Comment by Jerrynicki** [comment]
> woher kennst du bitte einen bot der "vore-mention-bot" heißt

von r/discord_irl
