### ISSUE TITLE
$status merken und Standard-Status mit Command anzeigen

### ISSUE THREAD

**Issue by Jerrynicki** [TheLastZombie/ich_iel#23]
Der Bot sollte sich den letzten eingestellten Status merken und bei einem Neustart wieder setzen.
Der normale Status könntedann durch einen extra Command (z.B. $stats) einsehbar sein.

Nur eine Idee

**Comment by TheLastZombie** [comment]
Ich wollte das mit dem Paste eh schon länger mal so umschreiben, dass nicht nur commands, sondern auch andere Daten gespeichert werden

**Comment by TheLastZombie** [comment]
Hab jetzt keinen extra Command dafür gemacht, die Info kann man ja noch mit $about/$hilfe/$help einsehen
