### ISSUE TITLE
Öffentliches $eval mit safe-eval lol

### ISSUE THREAD

**Issue by TheLastZombie** [TheLastZombie/ich_iel#26]
https://github.com/hacksparrow/safe-eval

**Comment by Jerrynicki** [comment]
ich dachte das wäre ein commit, fick dich

**Comment by TheLastZombie** [comment]
Das ist bescheuert, man könnte den Bot trotzdem sich abmelden lassen und das alles

**Comment by Jerrynicki** [comment]
uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu uwu

**Comment by nichtdasleo** [comment]
@TheLastZombie

**Comment by TheLastZombie** [comment]
@nichtdasleo

**Comment by nichtdasleo** [comment]
@TheLastZombie

**Comment by TheLastZombie** [comment]
Erklärt mir mal warum ich einen öffentlichen eval-Command machen sollte, und dann baut einen in LeOS und LifeBot ein

**Comment by TheLastZombie** [comment]
P.S. @nichtdasleo

**Comment by Jerrynicki** [comment]
weil du schw

**Comment by TheLastZombie** [comment]
Ja ne eben nicht

**Comment by Jerrynicki** [comment]
hurensohn mach das jetzt
dann halt in ner sandbox oder so

**Comment by TheLastZombie** [comment]
hurensohn mach du halt
ich bin eh noch im urlaub

**Comment by TheLastZombie** [comment]
ich könnte das aber mit vm machen damit du endlich dein fresn hältst

**Comment by TheLastZombie** [comment]
Weil ich das sonst nicht wiederfinde

```JavaScript
const {VM} = require("vm2");
var vmlog = "";
vmout = new VM({
    sandbox: {
        console: {
            log: function(str) {
            	    vmlog += str + "\n";
            	}
        }
    }
}).run(`
    console.log('VM2 console!');
    'VM2 output!';
`);
console.log("VM2 output: " + vmout);
console.log("VM2 console: " + vmlog);
```
