### ISSUE TITLE
$4 / $4chan command

### ISSUE THREAD

**Issue by TheLastZombie** [TheLastZombie/ich_iel#27]
Mit embeds und Bildern etc.

Weil .chan schw

**Comment by nichtdasleo** [comment]
was ist jetzt mit dem

**Comment by nichtdasleo** [comment]
machst du das noch @TheLastZombie

**Comment by TheLastZombie** [comment]
Aj

On September 19, 2018 1:57:06 PM GMT+02:00, nichtdasleo <notifications@github.com> wrote:
>machst du das noch @TheLastZombie 
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/TheLastZombie/ich_iel/issues/27#issuecomment-422774161

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
