### ISSUE TITLE
$nick global machen

### ISSUE THREAD

**Issue by Jerrynicki** [TheLastZombie/ich_iel#3]
Wäre ganz cool, wenn der Bot sich bei $nick auf allen Servern umbenennen würde.

**Comment by TheLastZombie** [comment]
Aus der discord.js-Dokumentation:
> Changing usernames in Discord is heavily rate limited, with only 2 requests every hour. Use this sparingly!

Implementiert in neuem Command $name, $nick bleibt. Siehe d64606f.

**Comment by Jerrynicki** [comment]
Da geht es doch aber um den Benutzernamen, nicht um den Nicknamen, oder?

**Comment by TheLastZombie** [comment]
Richtig.

**Comment by Jerrynicki** [comment]
Ich meinte eigentlich, dass der Bot durch die Liste von Servern iteriert und auf allen Servern seinen Nicknamen zum angegebenen Namen ändert

**Comment by TheLastZombie** [comment]
Gut, so könnte man das auch machen... Ich lass das hier mal offen, hinterlege disen Link (https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=guilds) und schau in der nahen Zukunft mal, was sich machen lässt.
