### ISSUE TITLE
duut duut sound wann

### ISSUE THREAD

**Issue by nichtdasleo** [TheLastZombie/ich_iel#30]

**Comment by TheLastZombie** [comment]
Du weißt genau wann

**Comment by Jerrynicki** [comment]
nie?

**Comment by nichtdasleo** [comment]
wann antwortet er diese fragen?

**Comment by Jerrynicki** [comment]
![image](https://user-images.githubusercontent.com/38357030/44997902-ef14f380-afb1-11e8-8e2d-9807a4f8c625.png)

**Comment by nichtdasleo** [comment]
dies ist so traurig, pingt ihn auf github @TheLastZombie

**Comment by Jerrynicki** [comment]
@TheLastZombie

**Comment by TheLastZombie** [comment]
Och leute

**Comment by TheLastZombie** [comment]
Fixed in #31 und 837bc72.

**Comment by nichtdasleo** [comment]
haha ja
