### ISSUE TITLE
hurensohn

### ISSUE THREAD

**Issue by Jerrynicki** [TheLastZombie/ich_iel#6]
https://i.imgur.com/uvj3sdG.png

**Comment by Jerrynicki** [comment]
![image](https://user-images.githubusercontent.com/38357030/43259848-fbc4090c-90d7-11e8-98b7-900cf29d3d28.png)

**Comment by TheLastZombie** [comment]
genau so

**Comment by Jerrynicki** [comment]
bist trotzdem ne schwucht

**Comment by TheLastZombie** [comment]
damit kann ich leben

**Comment by Jerrynicki** [comment]
![image](https://user-images.githubusercontent.com/38357030/43259906-2b9238ac-90d8-11e8-8fd0-b1b5f5fd4c3a.png)
huso

**Comment by TheLastZombie** [comment]
naja du hast ja angefangen, gell

**Comment by Jerrynicki** [comment]
fake

**Comment by TheLastZombie** [comment]
nein du

**Comment by Jerrynicki** [comment]
roesch du schwul

**Comment by TheLastZombie** [comment]
das hast du eben schon mal gesagt

**Comment by Jerrynicki** [comment]
benis

**Comment by TheLastZombie** [comment]
was war das denn

**Comment by Jerrynicki** [comment]
deine mama

**Comment by TheLastZombie** [comment]
chat in discord :verbessern:
chat in github issues :fickgehzurueck:

**Comment by nichtdasleo** [comment]
haha aj

**Comment by nichtdasleo** [comment]
lass uns hier reden

**Comment by TheLastZombie** [comment]
bitte nciht

**Comment by Jerrynicki** [comment]
mund jetzt
